### ISSUE TITLE
Language is Finnish in the IANSEO menu

### ISSUE THREAD

**Issue by kjetil-kilhavn** [mikkhola/ianseo#1]
First of all THANK YOU! I finally have IANSEO running.
One of the menus is in Finnish. If the translation from Google Translate can be trusted (with a little bit of sanity adjustment) this menu is specific to Finland's national archery association. Is that correct, or is it just 'your' version of a menu which should also exist in e.g. a Norwegian version?
If it should also exist in Norwegian, this is a bug report. Otherwise it is just a THANK YOU and can be closed immediately :-)

**Comment by mikkhola** [comment]
Sorry for the late reply. The Finnish language is provided by our Finnish Archery Association. I created a separate Docker image for FI and the default image is based on EN.
