### ISSUE TITLE
Base version is outdated; upgrade stalls; where are local files

### ISSUE THREAD

**Issue by kellyatkinson** [mikkhola/ianseo#3]
Thanks for making this image!

I can install it fine but the base IANSEO version is now well out of date (2017.01.01). The software correctly triggers an update when it is first installed, but the update hangs.

I have forked this into a new repo which has an updated IANSEO version and no Finnish customisations.

**Comment by mikkhola** [comment]
Thanks Kelly, I updated the image based on your changes. I also removed the Finnish language from the default image and created a separate image for FI lang.
